language: node_js
sudo: required
node_js: '9'
addons:
  firefox: latest
  chrome: stable
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@latest
install:
  - npm install   
script: npm run test